### ISSUE TITLE
Profile regeneration and Old simc build reported

### ISSUE THREAD

**Issue by renanthera** [Bloodmallet/bloodmallet_web_frontend#112]
Issues are two-fold:

- Profile regeneration doesn't necessarily occur prior to execution of sims used to populate the site, which can result in stale profiles being used.

It would be appreciated, if profile regeneration could occur at least locally, as it would guarantee most-up-to-date generated profiles are being used. Additionally, it saves additional PRs to the simc repository that would sometimes be necessary to avoid mixing generated and non-generated changes.

- Builds used for execution of sims are at least sometimes much older than listed sim date.

Is this just a case of "the sims take a very very long time to run", resulting in this seemingly unreasonably old build being reported?

<details>
<summary>Resulting issues</summary>

The latest [Brewmaster](https://bloodmallet.com/chart/monk/brewmaster/tier_set/castingpatchwerk) sims, as of writing this issue was most recently rerun 2023-07-22 04:22 UTC with commit [0a51857](https://github.com/simulationcraft/simc/commit/0a518573d095fd95d4b55abf5811deacd716e342).

The talent string used in the T30 Brewmaster profile as of that commit is the first talent string in the following pair. The second talent string is the one provided by all of the "Copy to Clipboard" talent tree embeds. One would expect these two strings to be identical.

[BwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAgkCtSSSgkkWjAAAAkWSIRiEpVkk0SkSCQrRkWalQA](https://github.com/simulationcraft/simc/blob/0a518573d095fd95d4b55abf5811deacd716e342/profiles/generators/Tier30/T30_Generate_Monk.simc#L8C9-L8C87)
BwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAgkCtSSSgkkWjAAAAkSSkEJSQRSikkSCQrIRapJE

Additionally, the build commit is ~4 days older than the most recent time of rerun.
</details>

**Comment by Bloodmallet** [comment]
Greetings,
when the generator files in SimulationCraft are updated, a follow-up commit should regenerate the profiles. Without this regeneration tools or workflows that depend on the generated profiles will use a different state than intended. E.g.:
- bloodmallet charts
- simulationcraft.org stacked chart

Regenerating profiles on the fly is not a good idea, because they then no longer represent the state of the repository of that commit. Staying in sync with what is present each repository is valuable and makes understanding what's going on simpler to follow.

Worker Images are regenerated daily. Chart data is regenerated [twice a week at the moment](https://github.com/Bloodmallet/bloodmallet_web_frontend/blob/develop/cron.yaml#L8). The latest created Worker Image is used to do so. I'll investigate further why an older commit was used. Thank you for bringing this up.

**Comment by Bloodmallet** [comment]
> the build commit is ~4 days older than the most recent time of rerun

I found the underlaying issue. While images were recreated daily, storing them broke a few days ago. A new one was created just now. I'm regenerating all charts with the new image as soon as possible.

**Comment by renanthera** [comment]
I would argue that generated file state is rather meaningless, given how trivial regen is [in this case], but that's kinda beyond the point. Thanks for the feedback, I'll make sure to PR those [profile regens] as well in the future.
