### ISSUE TITLE
Simulate full soulbind trees instead of adding up individual trait/conduit sims

### ISSUE THREAD

**Issue by nzall** [Bloodmallet/bloodmallet_web_frontend#92]
After discussing this with the author over Discord DMs, I was asked to log a ticket as an official request.

Now that 80 Renown is easily attainable by anyone and there is a catchup item for ilvl 200 conduits, the potential search space for conduits can be sufficiently reduced that it should be feasible to sim entire soulbind trees instead of individual traits that are added together, improving accuracy of the baseline sims.

suggested conduit levels:

200 since it's easily attainable by anyone with 80 renown;
226 since it's the highest from M+ and relatively easily attainable by those willing to put in the effort;
252 since it's the highest attainable overall.

Other levels might also make sense if the sim budget permits it.

**Comment by Bloodmallet** [comment]
Thank you for the suggestion. As written in DMs, I'll have a look at this and its doability. I'll post updates.

**Comment by Bloodmallet** [comment]
Alright here are some thoughts about this:
One full tree of non-conduit nodes won't cut it, because some of those dps nodes are "shared" with potency conduit slots. This means that there will be multiple full trees to simulate. Some with 2 potency conduits some with 3. Maybe there are even some with only one? I didn't check all trees for that yet. Let's assume the worst for now.
This means that whatever we're doing with Conduits needs to be done thrice in simulations.
- Trees per soulbind: 3

Next up are conduits. After having a quick look at my conduit charts I wonder when I broke some of them to suddenly appear in inappropriate charts. o_O Gotta fix that. But back on track: Something like 6 Conduits per spec are available.
- Conduits: 6

So taking the above into account we're probably looking at
- 1 tree and 3 unique conduits in any order out of 6 = 20
- 1 tree and 2 unique conduits in any order out of 6 = 15
- 1 tree and 1 conduit of 6 = 6

So we're looking at approximately 41 simulations per Conduit level. If we follow the 200, 226, 252 suggestion that would leave us with 123 profiles for each soulbind. 4 covenants, 3 soulbinds, that's 1476 profiles per spec. That's a lot. 😨

**Comment by nzall** [comment]
I think you overestimate how many trees per soulbind there are. Pelagos has 1 viable path for DPS because neither of his paths with 2 potency conduits has a DPS trait in place of the third potency conduit. Kleia and Mikanikos have 2 each. Marileth has 2, Emeni has 2, Heirmir has 2. I haven't checked Night Fae or Venthyr yet, but I suspect they follow similar estimates.

Related to conduits: Every spec has 4 potency conduits. Then there is a generic conduit per covenant, plus an additional potency conduit for classes with a tanking spec, so only half the classes have 6 conduits. Plus, each of the trees with 2 potency conduits as paths only needs to simulate 2 conduits, not 3, which also drastically 

So I think the final math will be significantly lower than the stated 1476 number.

**Comment by Bloodmallet** [comment]
You're right about that estimation being the upper bound. I'll see if I can whip up a combination creator later today, that does nothing but count these things. If I get it to work I'll provide a table with that data.

**Comment by nzall** [comment]
Pelagos has 1 viable path, with 3 potency conduits (viable being the maximum of potency slots and throughput traits). Theotar and Nadjia have 3: 1 with 3 potency and 2 with 2 potencies. The remaining 9 have 1 path with 3 potencies and 1 path with 2 potencies. so that is 12 paths with 3 potencies, and 11 paths with 2 potencies.

There are 9 DPS specs with 6 potency conduit options (4 spec specific, the covenant conduit and the tank conduit), the remaining The remaining 15 specs have 5 options.

If you have 6 potency conduits and 3 conduit slots, that is 6*5*4 = 120 profiles, * 12 paths, equals 1440 profiles.

6 conduits and 2 slots is 30 profiles per path, or 330 profiles across all paths.

5 conduits and 3 conduit slots is 5*4*3 = 60 profiles, or 720 profiles across all paths.

5 conduits and 2 slots is 20 profiles, or 220 profiles across all paths.

So that is a total of ((1440+330)*9 + (720+220)*15) = 30,030 profiles across all specs and soulbinds according to this math. So 90,090 when simming 3 levels of conduits.

**Comment by Bloodmallet** [comment]
Soulbind trees were reworked to simulate full trees. This should now show the actual winners, including all synergies available within a tree.
